<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\ApprovalMenu;
use App\Models\ApprovalTenant;
use App\Models\Categorie;
use App\Models\PaymentMethod;
use App\Models\PickupSlot;
use App\Models\Product;
use App\Models\Reservation;
use App\Models\Tenant;
use App\Models\TenantWallet;
use App\Models\User;
use App\Models\UserTenant;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        // User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);
        
        Categorie::insert([
            [
                'name' => 'Makanan',
                'slug' => 'makanan',
                'description' => 'Kategori makanan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minuman',
                'slug' => 'minuman',
                'description' => 'Kategori minuman',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Snack',
                'slug' => 'snack',
                'description' => 'Kategori snack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dessert',
                'slug' => 'dessert',
                'description' => 'Kategori dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Admin::insert([
            'username' => "admin",
            'email' => "admin@gmail.com",
            'email_verified_at' => now(),
            'password' => Hash::make('password'),
            'remember_token' => Str::random(10),
        ]);
        
        User::insert([
            [
                'name' => 'Andi Saputra',
                'email' => 'andi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tio Mayesa',
                'email' => 'tio@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alif Ghazy',
                'email' => 'alif@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        UserTenant::insert([
            [
                'nim' => '20231020003',
                'name' => 'Dennis',
                'prodi' => 'Teknik Informatika',
                'semester' => '6',
                'email' => 'dennis@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'isTenant' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '20231020041',
                'name' => 'Tio Mayesa',
                'prodi' => 'Teknik Informatika',
                'semester' => '6',
                'email' => 'tio@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'isTenant' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '20231020045',
                'name' => 'Alif Ghazy',
                'prodi' => 'Teknik Informatika',
                'semester' => '6',
                'email' => 'alif@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'isTenant' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            [
                'nim' => '20241290005',
                'name' => 'Muhammad Divo',
                'prodi' => 'Manajemen Bisnis',
                'semester' => '4',
                'email' => 'divo@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'isTenant' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '20241290003',
                'name' => 'Lina Apriliya',
                'prodi' => 'Manajemen Bisnis',
                'semester' => '4',
                'email' => 'lina@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'isTenant' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '20231020008',
                'name' => 'Marcellino Standlie',
                'prodi' => 'Teknik Informatika',
                'semester' => '6',
                'email' => 'marcel@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '081953312187',
                'isTenant' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        Reservation::insert([
            // 1. created_at: 2026-07-05 08:00:00 (ID Auto-increment: 1) Ended
            [
                'user_id' => 4,
                'start_date' => '2026-07-05',        
                'end_date' => '2026-07-21',        
                'statusApprove' => 1,        
                'is_acknowledged' => 0,   
                'activated_at' => '2026-07-05 09:15:00',    
                'is_ended' => 1,    
                'reasons' => null,    
                'created_at' => '2026-07-05 08:00:00',
                'updated_at' => '2026-07-05 09:15:00',
            ],
            // 2. created_at: 2026-07-06 08:00:00 (ID Auto-increment: 2) Ended
            [
                'user_id' => 5,
                'start_date' => '2026-07-06',        
                'end_date' => '2026-07-21',        
                'statusApprove' => 1,        
                'is_acknowledged' => 0,        
                'activated_at' => '2026-07-06 09:30:00',    
                'is_ended' => 1,    
                'reasons' => null,    
                'created_at' => '2026-07-06 08:00:00',
                'updated_at' => '2026-07-06 09:30:00',
            ],
            // 3. created_at: 2026-07-12 09:30:00 (ID Auto-increment: 3) Reject
            [
                'user_id' => 1,
                'start_date' => '2026-07-12',        
                'end_date' => '2026-07-22',        
                'statusApprove' => 0,        
                'is_acknowledged' => 1,        
                'activated_at' => null,    
                'is_ended' => 0,    
                'reasons' => 'Dokumen persyaratan tenant tidak lengkap',    
                'created_at' => '2026-07-12 09:30:00',
                'updated_at' => '2026-07-12 11:00:00',
            ],
            // 4. created_at: 2026-08-01 08:44:11 (ID Auto-increment: 4) Aktif
            [
                'user_id' => 1,
                'start_date' => '2026-08-01',        
                'end_date' => '2026-08-28',        
                'statusApprove' => 1,        
                'is_acknowledged' => 0,        
                'activated_at' => '2026-08-01 10:39:51',    
                'is_ended' => 0,    
                'reasons' => null,    
                'created_at' => '2026-08-01 08:44:11',
                'updated_at' => '2026-08-01 10:39:51',
            ],
            // 5. created_at: 2026-08-01 09:44:11 (ID Auto-increment: 5) Aktif
            [
                'user_id' => 2,
                'start_date' => '2026-08-03',        
                'end_date' => '2026-08-26',        
                'statusApprove' => 1,        
                'is_acknowledged' => 0,        
                'activated_at' => '2026-08-01 10:24:21',    
                'is_ended' => 0,    
                'reasons' => null,   
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 10:24:21', 
            ],
            // 6. created_at: 2026-08-01 09:44:11 (ID Auto-increment: 6) Aktif
            [
                'user_id' => 6,
                'start_date' => '2026-08-01',        
                'end_date' => '2026-08-11',        
                'statusApprove' => 1,        
                'is_acknowledged' => 0,        
                'activated_at' => '2026-08-01 10:24:21',    
                'is_ended' => 0,    
                'reasons' => null,   
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 10:24:21', 
            ],
            // 7. created_at: 2026-08-05 09:30:00 (ID Auto-increment: 7) Reject
            [
                'user_id' => 5,
                'start_date' => '2026-08-05',        
                'end_date' => '2026-08-12',        
                'statusApprove' => 0,        
                'is_acknowledged' => 0,        
                'activated_at' => null,    
                'is_ended' => 0,    
                'reasons' => 'Slot booth pada tanggal yang diajukan sudah didahului',    
                'created_at' => '2026-08-05 09:30:00',
                'updated_at' => '2026-08-10 11:00:00',
            ],
        ]);
        
        ApprovalTenant::insert([
            // Tenant ID: 1 (Reservasi ID 1 - Ended)
            [
                'tenant_code' => 'C',
                'reservation_id' => 1,
                'store_name' => 'Food box',        
                'slug' => 'food-box',        
                'description' => 'Food box - Menyediakan Aneka Menu Box Makanan Siap Saji',        
                'phone' => '081953312187',    
                'tenant_img' => 'approval_tenant/food-box.jpg',   
                'created_at' => '2026-07-05 08:00:00',
                'updated_at' => '2026-07-05 08:00:00', 
            ],
            // Tenant ID: 2 (Reservasi ID 2 - Ended)
            [
                'tenant_code' => 'B',
                'reservation_id' => 2,
                'store_name' => 'Food box 2',        
                'slug' => 'food-box-2',        
                'description' => 'Food box - Menyediakan Aneka Menu Box Makanan Siap Saji',        
                'phone' => '081953312187',    
                'tenant_img' => 'approval_tenant/food-box-2.jpg',   
                'created_at' => '2026-07-06 08:00:00',
                'updated_at' => '2026-07-06 08:00:00', 
            ],
            // Tenant ID: 3 (Reservasi ID 3 - Reject)
            [
                'tenant_code' => 'A',
                'reservation_id' => 3,
                'store_name' => 'Loaftory Coffe',        
                'slug' => 'loaftory-coffe',        
                'description' => 'Affordable Tapi Tetap Berkualitas',        
                'phone' => '081953312187',    
                'tenant_img' => 'approval_tenant/loaftory-coffe.png',   
                'created_at' => '2026-07-12 09:30:00',
                'updated_at' => '2026-07-12 09:30:00', 
            ],
            // Tenant ID: 4 (Reservasi ID 4 - Aktif)
            [
                'tenant_code' => 'A',
                'reservation_id' => 4,
                'store_name' => 'Suap n Sip',        
                'slug' => 'suap-n-sip',        
                'description' => 'Open Pre Order Sup n Sips Menu Berbagai Rice Bowl & Cheesecuit Aneka Rasa',        
                'phone' => '081953312187',    
                'tenant_img' => 'approval_tenant/suap-n-sip.jpg',   
                'created_at' => '2026-08-01 08:44:11',
                'updated_at' => '2026-08-01 08:44:11', 
            ],
            // Tenant ID: 5 (Reservasi ID 5 - Aktif)
            [
                'tenant_code' => 'B',
                'reservation_id' => 5,
                'store_name' => "Baca's Dimsum",        
                'slug' => "bacas-dimsum",        
                'description' => 'Rasakan Sensasi Lezatnya Dimsum dengan Toping Berbaai Varian',        
                'phone' => '081953312187',    
                'tenant_img' => 'approval_tenant/bacas-dimsum.jpg',   
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11', 
            ],
            // Tenant ID: 6 (Reservasi ID 6 - Aktif)
            [
                'tenant_code' => 'C',
                'reservation_id' => 6,
                'store_name' => "Seblak Bahagia",        
                'slug' => "seblak-bahagia",        
                'description' => 'Seblak & Sate Asin',        
                'phone' => '081953312187',    
                'tenant_img' => 'approval_tenant/seblak-bahagia.jpg',   
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11', 
            ],
            // Tenant ID: 7 (Reservasi ID 7 - Reject)
            [
                'tenant_code' => 'C',
                'reservation_id' => 7,
                'store_name' => 'Mol Cimol',        
                'slug' => 'mol-cimol',        
                'description' => 'Cimol Kuah Keju Creamy',        
                'phone' => '081953312187',    
                'tenant_img' => 'approval_tenant/mol-cimol.png',   
                'created_at' => '2026-08-05 09:30:00',
                'updated_at' => '2026-08-05 09:30:00', 
            ]     
        ]);
        
        ApprovalMenu::insert([
            // Tenant ID 1: Foodbox (Reservasi ID 1: 2026-07-05 08:00:00)
            [
                'tenant_id' => 1,
                'category_id' => 1,
                'name' => 'Foodbox Ayam Geprek',
                'slug' => 'foodbox-ayam-geprek',
                'description' => 'Nasi + Ayam Geprek + Sambal',
                'price' => 15000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/foodbox-ayam-geprek.jpeg',
                'created_at' => '2026-07-05 08:00:00',
                'updated_at' => '2026-07-05 08:00:00',
            ],
            [
                'tenant_id' => 1,
                'category_id' => 1,
                'name' => 'Foodbox Ayam Bakar',
                'slug' => 'foodbox-ayam-bakar',
                'description' => 'Nasi + Ayam Bakar + Lalapan + Sambal',
                'price' => 15000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/foodbox-ayam-bakar.jpg',
                'created_at' => '2026-07-05 08:00:00',
                'updated_at' => '2026-07-05 08:00:00',
            ],
            [
                'tenant_id' => 1,
                'category_id' => 2,
                'name' => 'Es Teh Manis',
                'slug' => 'es-teh-manis',
                'description' => null,
                'price' => 3000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/es-teh-manis.webp',
                'created_at' => '2026-07-05 08:00:00',
                'updated_at' => '2026-07-05 08:00:00',
            ],
        
            // Tenant ID 2: Foodbox 2 (Reservasi ID 2: 2026-07-06 08:00:00)
            [
                'tenant_id' => 2,
                'category_id' => 1,
                'name' => 'Foodbox Ayam Geprek',
                'slug' => 'foodbox-2-ayam-geprek',
                'description' => 'Nasi + Ayam Geprek + Sambal',
                'price' => 15000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/foodbox-2-ayam-geprek.jpeg',
                'created_at' => '2026-07-06 08:00:00',
                'updated_at' => '2026-07-06 08:00:00',
            ],
            [
                'tenant_id' => 2,
                'category_id' => 1,
                'name' => 'Foodbox Ayam Bakar',
                'slug' => 'foodbox-2-ayam-bakar',
                'description' => 'Nasi + Ayam Bakar + Lalapan + Sambal',
                'price' => 17000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/foodbox-2-ayam-bakar.jpg',
                'created_at' => '2026-07-06 08:00:00',
                'updated_at' => '2026-07-06 08:00:00',
            ],
            [
                'tenant_id' => 2,
                'category_id' => 2,
                'name' => 'Es Teh Manis',
                'slug' => 'es-teh-manis-2',
                'description' => null,
                'price' => 3000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/es-teh-manis-2.webp',
                'created_at' => '2026-07-06 08:00:00',
                'updated_at' => '2026-07-06 08:00:00',
            ],
        
            // Tenant ID 3: Loaftory Coffe (Reservasi ID 3: 2026-07-12 09:30:00)
            [
                'tenant_id' => 3,
                'category_id' => 1,
                'name' => 'Roti Boo',
                'slug' => 'roti-boo',
                'description' => null,
                'price' => 7000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/roti-boo.jpg',
                'created_at' => '2026-07-12 09:30:00',
                'updated_at' => '2026-07-12 09:30:00',
            ],
            [
                'tenant_id' => 3,
                'category_id' => 2,
                'name' => 'Dalgonice',
                'slug' => 'dalgonice',
                'description' => null,
                'price' => 12000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/dalgonice.jpg',
                'created_at' => '2026-07-12 09:30:00',
                'updated_at' => '2026-07-12 09:30:00',
            ],
        
            // Tenant ID 4: Sup n Sip (Reservasi ID 4: 2026-08-01 08:44:11)
            [
                'tenant_id' => 4,
                'category_id' => 1,
                'name' => 'Rice Bowl Asam Manis',
                'slug' => 'rice-bowl-asam-manis',
                'description' => null,
                'price' => 10000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/rice-bowl-asam-manis.jpg',
                'created_at' => '2026-08-01 08:44:11',
                'updated_at' => '2026-08-01 08:44:11',
            ],
            [
                'tenant_id' => 4,
                'category_id' => 1,
                'name' => 'Rice Bowl BBQ',
                'slug' => 'rice-bowl-bbq',
                'description' => null,
                'price' => 10000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/rice-bowl-bbq.webp',
                'created_at' => '2026-08-01 08:44:11',
                'updated_at' => '2026-08-01 08:44:11',
            ],
            [
                'tenant_id' => 4,
                'category_id' => 1,
                'name' => 'Rice Bowl Chili Padi',
                'slug' => 'rice-bowl-chili-padi',
                'description' => null,
                'price' => 10000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/rice-bowl-chili-padi.jpg',
                'created_at' => '2026-08-01 08:44:11',
                'updated_at' => '2026-08-01 08:44:11',
            ],
            [
                'tenant_id' => 4,
                'category_id' => 2,
                'name' => 'Es Jeruk',
                'slug' => 'es-jeruk',
                'description' => null,
                'price' => 5000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/es-jeruk.jpg',
                'created_at' => '2026-08-01 08:44:11',
                'updated_at' => '2026-08-01 08:44:11',
            ],
        
            // Tenant ID 5: Baca's Dimsum (Reservasi ID 5: 2026-08-01 09:44:11)
            [
                'tenant_id' => 5,
                'category_id' => 2,
                'name' => 'Dimsum Original',
                'slug' => 'dimsum-original',
                'description' => 'Dimsum Original isi 6 Include Chili Oil/Saus ',
                'price' => 20000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/dimsum-original.jpg',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            [
                'tenant_id' => 5,
                'category_id' => 1,
                'name' => 'Dimsun Mentai',
                'slug' => 'dimsun-mentai',
                'description' => 'Isi 8 Include Chili Oil/Saus',
                'price' => 30000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/dimsun-mentai.webp',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            [
                'tenant_id' => 5,
                'category_id' => 1,
                'name' => 'Dimsum Keju Lumer',
                'slug' => 'dimsum-keju-lumer',
                'description' => 'Dimsum Goreng Keju Lumer isi 5 Free Chili OIl/Saus Bankok',
                'price' => 30000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/dimsum-keju-lumer.webp',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            [
                'tenant_id' => 5,
                'category_id' => 1,
                'name' => 'Kentang Goreng',
                'slug' => 'kentang-goreng',
                'description' => null,
                'price' => 10000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/kentang-goreng.png',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            [
                'tenant_id' => 5,
                'category_id' => 2,
                'name' => 'Ice Tea',
                'slug' => 'ice-tea',
                'description' => null,
                'price' => 2000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/ice-tea.jpg',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            // Tenant ID 6: Seblak Bahagia (Reservasi ID 6: 2026-08-01 09:30:00)
            [
                'tenant_id' => 6,
                'category_id' => 1,
                'name' => 'Seblak Kuah Original',
                'slug' => 'seblak-kuah-original',
                'description' => 'Seblak Kuah Original',
                'price' => 10000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/seblak-kuah-original.webp',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            [
                'tenant_id' => 6,
                'category_id' => 1,
                'name' => 'Seblak Kuah Kari',
                'slug' => 'seblak-kuah-kari',
                'description' => 'Seblak Kuah Kari',
                'price' => 10000.00,
                'is_preorder' => 1,
                'product_img' => 'approval_menu/seblak-kuah-kari.webp',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            // Tenant ID 7: Mol Cimol (Reservasi ID 7: 2026-08-05 09:30:00)
            [
                'tenant_id' => 7,
                'category_id' => 1,
                'name' => 'Cimol Isi Keju',
                'slug' => 'cimol-isi-keju',
                'description' => 'Cimol Isi Keju',
                'price' => 5000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/cimol-isi-keju.jpeg',
                'created_at' => '2026-08-05 09:30:00',
                'updated_at' => '2026-08-05 09:30:00',
            ],
            [
                'tenant_id' => 7,
                'category_id' => 1,
                'name' => 'Cimol Kuah Keju',
                'slug' => 'cimol-kuah-keju',
                'description' => 'Cimol Kuah Keju',
                'price' => 10000.00,
                'is_preorder' => 0,
                'product_img' => 'approval_menu/cimol-kuah-keju.jpg',
                'created_at' => '2026-08-05 09:30:00',
                'updated_at' => '2026-08-05 09:30:00',
            ],
        ]);

        Tenant::insert([
            [
                'tenant_code' => 'A',
                'reservation_id' => 4,        
                'store_name' => 'Sup n Sip',        
                'slug' => 'sup-n-sip',        
                'description' => 'Open Pre Order Sup n Sips Menu Berbagai Rice Bowl & Cheesecuit Aneka Rasa',        
                'phone' => '081953312187',    
                'is_open' => 1,
                'tenant_img' => 'tenants/sup-n-sip.jpg',   
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
                'tenant_code' => 'B',
                'reservation_id' => 5,        
                'store_name' => "Baca's Dimsum",        
                'slug' => "bacas-dimsum",        
                'description' => 'Rasakan Sensasi Lezatnya Dimsum dengan Toping Berbaai Varian',        
                'phone' => '081953312187',    
                'is_open' => 1,    
                'tenant_img' => 'tenants/bacas-dimsum.jpg',   
                'created_at' => now(),
                'updated_at' => now(), 
            ],
            [
                'tenant_code' => 'C',
                'reservation_id' => 6,
                'store_name' => "Seblak Bahagia",        
                'slug' => "seblak-bahagia",        
                'description' => 'Seblak & Sate Asin',        
                'phone' => '081953312187',    
                'is_open' => 1, 
                'tenant_img' => 'tenants/seblak-bahagia.jpg',   
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11', 
            ],
        ]);

        Product::insert([
            [
                'tenant_id' => 1,
                'reservation_id' => 4,
                'category_id' => 1,
                'name' => 'Rice Bowl Asam Manis',
                'slug' => 'rice-bowl-asam-manis',
                'description' => null,
                'price' => 10000.00,
                'is_available' => 1,
                'is_preorder' => 1,
                'product_img' => 'products/rice-bowl-asam-manis.jpeg',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 1,
                'reservation_id' => 4,
                'category_id' => 1,
                'name' => 'Rice Bowl BBQ',
                'slug' => 'rice-bowl-bbq',
                'description' => null,
                'price' => 10000.00,
                'is_available' => 1,
                'is_preorder' => 1,
                'product_img' => 'products/rice-bowl-bbq.jpeg',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 1,
                'reservation_id' => 4,
                'category_id' => 1,
                'name' => 'Rice Bowl Chili Padi',
                'slug' => 'rice-bowl-chili-padi',
                'description' => null,
                'price' => 10000.00,
                'is_available' => 1,
                'is_preorder' => 1,
                'product_img' => 'products/rice-bowl-chili-padi.webp',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 1,
                'reservation_id' => 4,
                'category_id' => 2,
                'name' => 'Es Jeruk',
                'slug' => 'es-jeruk',
                'description' => null,
                'price' => 5000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/es-jeruk.jpg',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 2,
                'reservation_id' => 5,
                'category_id' => 2,
                'name' => 'Dimsum Original',
                'slug' => 'dimsum-original',
                'description' => 'Dimsum Original isi 6 Include Chili Oil/Saus ',
                'price' => 20000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/dimsum-original.jpg',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 2,
                'reservation_id' => 5,
                'category_id' => 2,
                'name' => 'Ice Tea',
                'slug' => 'ice-tea',
                'description' => null,
                'price' => 2000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/ice-tea.jpg',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 2,
                'reservation_id' => 5,
                'category_id' => 1,
                'name' => 'Dimsun Mentai',
                'slug' => 'dimsun-mentai',
                'description' => 'Isi 8 Include Chili Oil/Saus',
                'price' => 30000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/dimsun-mentai.webp',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 2,
                'reservation_id' => 5,
                'category_id' => 1,
                'name' => 'Dimsum Keju Lumer',
                'slug' => 'dimsum-keju-lumer',
                'description' => 'Dimsum Goreng Keju Lumer isi 5 Free Chili OIl/Saus Bankok',
                'price' => 30000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/dimsum-keju-lumer.webp',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 2,
                'reservation_id' => 5,
                'category_id' => 1,
                'name' => 'Kentang Goreng',
                'slug' => 'kentang-goreng',
                'description' => null,
                'price' => 10000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/kentang-goreng.png',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 3,
                'reservation_id' => 6,
                'category_id' => 1,
                'name' => 'Seblak Kuah Original',
                'slug' => 'seblak-kuah-original',
                'description' => 'Seblak Kuah Original',
                'price' => 10000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/seblak-kuah-original.webp',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
            [
                'tenant_id' => 3,
                'reservation_id' => 6,
                'category_id' => 1,
                'name' => 'Seblak Kuah Kari',
                'slug' => 'seblak-kuah-kari',
                'description' => 'Seblak Kuah Kari',
                'price' => 10000.00,
                'is_available' => 1,
                'is_preorder' => 0,
                'product_img' => 'products/seblak-kuah-kari.webp',
                'created_at' => '2026-08-01 09:44:11',
                'updated_at' => '2026-08-01 09:44:11',
            ],
        ]);

        PickupSlot::insert([
            [
                'tenant_id' => 1,
                'dayPickup' => 'Rabu',
                'start_time' => '08:30:00',
                'end_time' => '13:00:00',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
            [
                'tenant_id' => 1,
                'dayPickup' => 'Kamis',
                'start_time' => '08:30:00',
                'end_time' => '13:00:00',
                'created_at' =>  now(),
                'updated_at' =>  now(),
            ],
        ]);

        PaymentMethod::insert([
            [
                // 'tenant_id' => 1,
                'reservation_id' => 4,
                'type' => 'e_wallet',        
                'name_payment' => 'Dana',        
                'account_number' => '081953312187',        
                'account_name' => 'Dennis Saputra',        
                'created_at' => now(),
                'updated_at' => now(),  
            ],
            [
                // 'tenant_id' => 2,
                'reservation_id' => 5,
                'type' => 'bank_transfer',        
                'name_payment' => 'BCA',        
                'account_number' => '6404284274658',        
                'account_name' => 'Tio Mayesa',        
                'created_at' => now(),
                'updated_at' => now(),  
            ],
            [
                // 'tenant_id' => 3,
                'reservation_id' => 6,
                'type' => 'e_wallet',        
                'name_payment' => 'Dana',        
                'account_number' => '081953312187',        
                'account_name' => 'Marcellino Standlie',        
                'created_at' => now(),
                'updated_at' => now(),  
            ],
        ]);

        TenantWallet::insert([
            [
                'reservation_id' => 4,
                'tenant_code' => 'A',        
                'total_earned' => 0,        
                'total_paid_out' => 0,                 
                'created_at' => now(),
                'updated_at' => now(),  
            ],
            [
                'reservation_id' => 5,
                'tenant_code' => 'B',        
                'total_earned' => 0,        
                'total_paid_out' => 0,         
                'created_at' => now(),
                'updated_at' => now(),  
            ],
            [
                'reservation_id' => 6,
                'tenant_code' => 'C',        
                'total_earned' => 0,        
                'total_paid_out' => 0,        
                'created_at' => now(),
                'updated_at' => now(),  
            ],
        ]);
        
        // $this->call([
        //     ReservationSeeder::class,
        //     TenantSeeder::class,
        //     ProductSeeder::class,
        //     ApprovalTenantSeeder::class,
        //     ApprovalMenuSeeder::class,
        // ]);

        
    }
}
